//! Modello di costo delle operazioni tabellari: GENERATO da
//! `scripts/genera_costi_operazioni.py`, non si modifica a mano.
//!
//! Fonte: `data/misure/catalogo-memoria-v4.json` (campagna Windows v4 a
//! `24698d6`, `PeakWorkingSet64`; SHA-256 in [`SHA256_MISURE`]).
//!
//! Per operazione e variante, con `R` righe in ingresso (somma dei lati),
//! `B` byte Arrow in ingresso, `K = R * colonne d'uscita`, `P` = righe
//! sinistra per righe destra:
//!
//! ```text
//! picco = S * (a + max(r*R + c*B, r_s*R, c_l*B) + k*K + p*P)
//! ```
//!
//! - `y_i = max(budget_estimate_bytes_i, output_new_buffer_bytes_i, 0)`
//!   per ogni punto osservato di tutti i profili della variante;
//! - piano `a + r*R + c*B (+ k*K | p*P)`: il minimo (somma dei rapporti
//!   previsto/misurato) che copre ogni `y_i`, con `a <= min y` e `c >= 1`
//!   dove l'uscita puo' essere una copia intera degli ingressi;
//! - rami di estrapolazione in larghezza: `r_s` inviluppo per riga del
//!   profilo con le righe piu' strette, `c_l` inviluppo per byte di quello
//!   con le righe piu' larghe;
//! - `k` solo per `pivot` (senza rami), `p` solo per le superlineari
//!   (`cross_join`, `fuzzy_join`, senza altri termini);
//! - coefficienti in millesimi di byte, per eccesso; `S` =
//!   [`FATTORE_SICUREZZA`], per eccesso. Regole in `scripts/modello_costi.py`.
//!
//! Le varianti spilled sono misurate con `max_governed_memory_bytes` pari
//! a [`BUDGET_SPILL_MISURATO`]: il runner non passa ai kernel spilled un
//! margine piu' grande.
//!
//! Crescita per riga oltre la soglia in ogni profilo, fra gli ultimi
//! due campioni, per operazioni lineari nel modello (coperte fino al
//! campione piu' grande; oltre il dominio misurato, estrapolazione):
//!
//! - `table.date_extract` wide: 2.40
//! - `table.lookup` wide: 1.67
//! - `table.string_length` wide: 2.37

use crate::budget::{Costo, CostoOperazione};

/// SHA-256 delle misure da cui il modello e' generato.
pub const SHA256_MISURE: &str = "9057ae26a04f9c1868b9c99766f60a26147d80606b8e62f62d3255be9ba2bf07";

/// Fattore di sicurezza `S` come frazione (numeratore, denominatore).
pub const FATTORE_SICUREZZA: (u64, u64) = (3, 2);

/// `max_governed_memory_bytes` dei profili spilled misurati.
pub const BUDGET_SPILL_MISURATO: u64 = 67_108_864;

/// Un modello per operazione misurata, in ordine di id.
pub static COSTI: &[CostoOperazione] = &[
    CostoOperazione {
        op: "table.add_row_number",
        in_memoria: Costo {
            a: 207_531,
            r_millesimi: 24_426,
            c_millesimi: 0,
            r_stretta_millesimi: 39_732,
            c_larga_millesimi: 297,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.aggregate",
        in_memoria: Costo {
            a: 561_152,
            r_millesimi: 0,
            c_millesimi: 1_251,
            r_stretta_millesimi: 56_116,
            c_larga_millesimi: 1_331,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: Some(Costo {
            a: 1_161_379,
            r_millesimi: 0,
            c_millesimi: 1_066,
            r_stretta_millesimi: 174_490,
            c_larga_millesimi: 1_837,
            k_millesimi: 0,
            p_millesimi: 0,
        }),
        dipende_dai_dati: true,
        profili: &["distinct", "spilled_distinct", "spilled_wide", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.align_schema",
        in_memoria: Costo {
            a: 138_644,
            r_millesimi: 41_023,
            c_millesimi: 0,
            r_stretta_millesimi: 51_610,
            c_larga_millesimi: 585,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.anti_join",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 22_940,
            c_millesimi: 1_000,
            r_stretta_millesimi: 39_717,
            c_larga_millesimi: 504,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.asof_join",
        in_memoria: Costo {
            a: 56_373,
            r_millesimi: 12_971,
            c_millesimi: 1_000,
            r_stretta_millesimi: 41_780,
            c_larga_millesimi: 1_252,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.assert_cardinality",
        in_memoria: Costo {
            a: 4_096,
            r_millesimi: 164,
            c_millesimi: 0,
            r_stretta_millesimi: 410,
            c_larga_millesimi: 5,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.assert_foreign_key",
        in_memoria: Costo {
            a: 311_143,
            r_millesimi: 13_219,
            c_millesimi: 268,
            r_stretta_millesimi: 18_637,
            c_larga_millesimi: 577,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.assert_metadata",
        in_memoria: Costo {
            a: 8_192,
            r_millesimi: 0,
            c_millesimi: 68,
            r_stretta_millesimi: 820,
            c_larga_millesimi: 69,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.assert_not_null",
        in_memoria: Costo {
            a: 24_576,
            r_millesimi: 0,
            c_millesimi: 64,
            r_stretta_millesimi: 2_868,
            c_larga_millesimi: 67,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.assert_range",
        in_memoria: Costo {
            a: 28_672,
            r_millesimi: 661,
            c_millesimi: 7,
            r_stretta_millesimi: 3_687,
            c_larga_millesimi: 44,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.assert_regex",
        in_memoria: Costo {
            a: 438_272,
            r_millesimi: 410,
            c_millesimi: 0,
            r_stretta_millesimi: 44_237,
            c_larga_millesimi: 472,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.assert_schema",
        in_memoria: Costo {
            a: 28_672,
            r_millesimi: 410,
            c_millesimi: 0,
            r_stretta_millesimi: 3_277,
            c_larga_millesimi: 31,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.assert_unique",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 45_409,
            c_millesimi: 946,
            r_stretta_millesimi: 61_264,
            c_larga_millesimi: 1_224,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.bin",
        in_memoria: Costo {
            a: 232_562,
            r_millesimi: 84_879,
            c_millesimi: 0,
            r_stretta_millesimi: 108_135,
            c_larga_millesimi: 956,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.coalesce",
        in_memoria: Costo {
            a: 134_010,
            r_millesimi: 5_032,
            c_millesimi: 0,
            r_stretta_millesimi: 18_432,
            c_larga_millesimi: 197,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.concat",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 1_514,
            c_millesimi: 1_735,
            r_stretta_millesimi: 22_119,
            c_larga_millesimi: 1_773,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.concat_by_name",
        in_memoria: Costo {
            a: 1_541,
            r_millesimi: 1_484,
            c_millesimi: 1_741,
            r_stretta_millesimi: 24_372,
            c_larga_millesimi: 1_779,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.concat_columns",
        in_memoria: Costo {
            a: 271_831,
            r_millesimi: 0,
            c_millesimi: 571,
            r_stretta_millesimi: 80_692,
            c_larga_millesimi: 860,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.conditional",
        in_memoria: Costo {
            a: 240_302,
            r_millesimi: 48_470,
            c_millesimi: 0,
            r_stretta_millesimi: 68_813,
            c_larga_millesimi: 773,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.cross_join",
        in_memoria: Costo {
            a: 253_952,
            r_millesimi: 0,
            c_millesimi: 0,
            r_stretta_millesimi: 0,
            c_larga_millesimi: 0,
            k_millesimi: 0,
            p_millesimi: 159_289,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.date_add",
        in_memoria: Costo {
            a: 558_997,
            r_millesimi: 0,
            c_millesimi: 631,
            r_stretta_millesimi: 115_098,
            c_larga_millesimi: 1_227,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.date_diff",
        in_memoria: Costo {
            a: 96_753,
            r_millesimi: 0,
            c_millesimi: 185,
            r_stretta_millesimi: 27_034,
            c_larga_millesimi: 289,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.date_extract",
        in_memoria: Costo {
            a: 208_411,
            r_millesimi: 0,
            c_millesimi: 407,
            r_stretta_millesimi: 58_983,
            c_larga_millesimi: 629,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.date_format",
        in_memoria: Costo {
            a: 578_877,
            r_millesimi: 0,
            c_millesimi: 601,
            r_stretta_millesimi: 114_279,
            c_larga_millesimi: 1_218,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.dedup_advanced",
        in_memoria: Costo {
            a: 50_967,
            r_millesimi: 58_612,
            c_millesimi: 1_000,
            r_stretta_millesimi: 77_824,
            c_larga_millesimi: 1_424,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.distinct",
        in_memoria: Costo {
            a: 61_647,
            r_millesimi: 58_553,
            c_millesimi: 1_000,
            r_stretta_millesimi: 90_932,
            c_larga_millesimi: 1_427,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: Some(Costo {
            a: 928_882,
            r_millesimi: 42_204,
            c_millesimi: 1_797,
            r_stretta_millesimi: 302_285,
            c_larga_millesimi: 2_695,
            k_millesimi: 0,
            p_millesimi: 0,
        }),
        dipende_dai_dati: false,
        profili: &[
            "distinct",
            "narrow",
            "spilled_distinct",
            "spilled_wide",
            "wide",
        ],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.drop_columns",
        in_memoria: Costo {
            a: 57_344,
            r_millesimi: 0,
            c_millesimi: 68,
            r_stretta_millesimi: 5_735,
            c_larga_millesimi: 75,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.except",
        in_memoria: Costo {
            a: 905_216,
            r_millesimi: 22_832,
            c_millesimi: 1_561,
            r_stretta_millesimi: 45_261,
            c_larga_millesimi: 1_602,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: Some(Costo {
            a: 634_314,
            r_millesimi: 0,
            c_millesimi: 1_000,
            r_stretta_millesimi: 78_644,
            c_larga_millesimi: 669,
            k_millesimi: 0,
            p_millesimi: 0,
        }),
        dipende_dai_dati: false,
        profili: &[
            "distinct",
            "narrow",
            "spilled_distinct",
            "spilled_wide",
            "wide",
        ],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.explode",
        in_memoria: Costo {
            a: 484_239,
            r_millesimi: 84_287,
            c_millesimi: 0,
            r_stretta_millesimi: 132_711,
            c_larga_millesimi: 2_138,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.expression",
        in_memoria: Costo {
            a: 197_974,
            r_millesimi: 73_592,
            c_millesimi: 0,
            r_stretta_millesimi: 93_389,
            c_larga_millesimi: 917,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.fill_na",
        in_memoria: Costo {
            a: 111_916,
            r_millesimi: 5_603,
            c_millesimi: 0,
            r_stretta_millesimi: 16_794,
            c_larga_millesimi: 179,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.filter",
        in_memoria: Costo {
            a: 36_864,
            r_millesimi: 0,
            c_millesimi: 1_000,
            r_stretta_millesimi: 29_901,
            c_larga_millesimi: 738,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.flatten_json",
        in_memoria: Costo {
            a: 216_923,
            r_millesimi: 0,
            c_millesimi: 603,
            r_stretta_millesimi: 78_234,
            c_larga_millesimi: 834,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.formula",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 23_880,
            c_millesimi: 0,
            r_stretta_millesimi: 23_880,
            c_larga_millesimi: 249,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.fuzzy_join",
        in_memoria: Costo {
            a: 421_888,
            r_millesimi: 0,
            c_millesimi: 0,
            r_stretta_millesimi: 0,
            c_larga_millesimi: 0,
            k_millesimi: 0,
            p_millesimi: 286_720,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["distinct", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.hmac_sha256",
        in_memoria: Costo {
            a: 818_290,
            r_millesimi: 72_591,
            c_millesimi: 0,
            r_stretta_millesimi: 154_420,
            c_larga_millesimi: 1_646,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.intersect",
        in_memoria: Costo {
            a: 668_811,
            r_millesimi: 61_354,
            c_millesimi: 1_000,
            r_stretta_millesimi: 54_477,
            c_larga_millesimi: 968,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: Some(Costo {
            a: 642_506,
            r_millesimi: 0,
            c_millesimi: 1_000,
            r_stretta_millesimi: 79_053,
            c_larga_millesimi: 658,
            k_millesimi: 0,
            p_millesimi: 0,
        }),
        dipende_dai_dati: false,
        profili: &[
            "distinct",
            "narrow",
            "spilled_distinct",
            "spilled_wide",
            "wide",
        ],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.join",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 82_115,
            c_millesimi: 1_000,
            r_stretta_millesimi: 98_892,
            c_larga_millesimi: 1_028,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.limit",
        in_memoria: Costo {
            a: 8_192,
            r_millesimi: 0,
            c_millesimi: 75,
            r_stretta_millesimi: 1_639,
            c_larga_millesimi: 76,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.lookup",
        in_memoria: Costo {
            a: 200_704,
            r_millesimi: 13_435,
            c_millesimi: 0,
            r_stretta_millesimi: 20_071,
            c_larga_millesimi: 214,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.mask_data",
        in_memoria: Costo {
            a: 73_333,
            r_millesimi: 5_577,
            c_millesimi: 72,
            r_stretta_millesimi: 19_661,
            c_larga_millesimi: 210,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.md5_hash",
        in_memoria: Costo {
            a: 255_318,
            r_millesimi: 45_739,
            c_millesimi: 0,
            r_stretta_millesimi: 71_271,
            c_larga_millesimi: 760,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.melt",
        in_memoria: Costo {
            a: 215_144,
            r_millesimi: 40_745,
            c_millesimi: 0,
            r_stretta_millesimi: 61_031,
            c_larga_millesimi: 664,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.pivot",
        in_memoria: Costo {
            a: 364_607,
            r_millesimi: 22_868,
            c_millesimi: 1_000,
            r_stretta_millesimi: 0,
            c_larga_millesimi: 0,
            k_millesimi: 7_649,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["distinct", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.reconcile",
        in_memoria: Costo {
            a: 243_077,
            r_millesimi: 22_453,
            c_millesimi: 218,
            r_stretta_millesimi: 30_106,
            c_larga_millesimi: 590,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.rename",
        in_memoria: Costo {
            a: 65_536,
            r_millesimi: 820,
            c_millesimi: 0,
            r_stretta_millesimi: 7_373,
            c_larga_millesimi: 70,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.reorder_columns",
        in_memoria: Costo {
            a: 57_344,
            r_millesimi: 0,
            c_millesimi: 0,
            r_stretta_millesimi: 5_735,
            c_larga_millesimi: 62,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.replace",
        in_memoria: Costo {
            a: 97_643,
            r_millesimi: 5_801,
            c_millesimi: 0,
            r_stretta_millesimi: 15_565,
            c_larga_millesimi: 166,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.rolling_window",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 20_942,
            c_millesimi: 2_133,
            r_stretta_millesimi: 71_271,
            c_larga_millesimi: 2_286,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.sample",
        in_memoria: Costo {
            a: 155_648,
            r_millesimi: 8_070,
            c_millesimi: 0,
            r_stretta_millesimi: 15_565,
            c_larga_millesimi: 249,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.select_columns",
        in_memoria: Costo {
            a: 57_344,
            r_millesimi: 0,
            c_millesimi: 64,
            r_stretta_millesimi: 6_144,
            c_larga_millesimi: 71,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.semi_join",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 24_316,
            c_millesimi: 1_000,
            r_stretta_millesimi: 44_032,
            c_larga_millesimi: 973,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.sha256_hash",
        in_memoria: Costo {
            a: 808_278,
            r_millesimi: 72_773,
            c_millesimi: 0,
            r_stretta_millesimi: 153_600,
            c_larga_millesimi: 1_637,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.sort",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 18_596,
            c_millesimi: 1_000,
            r_stretta_millesimi: 43_008,
            c_larga_millesimi: 967,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: Some(Costo {
            a: 665_808,
            r_millesimi: 947,
            c_millesimi: 1_000,
            r_stretta_millesimi: 161_383,
            c_larga_millesimi: 1_133,
            k_millesimi: 0,
            p_millesimi: 0,
        }),
        dipende_dai_dati: false,
        profili: &[
            "distinct",
            "narrow",
            "spilled_distinct",
            "spilled_wide",
            "wide",
        ],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.split_column",
        in_memoria: Costo {
            a: 176_813,
            r_millesimi: 0,
            c_millesimi: 266,
            r_stretta_millesimi: 42_599,
            c_larga_millesimi: 454,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.stable_fingerprint",
        in_memoria: Costo {
            a: 821_476,
            r_millesimi: 72_682,
            c_millesimi: 0,
            r_stretta_millesimi: 154_829,
            c_larga_millesimi: 1_650,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.statistics",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 0,
            c_millesimi: 1_335,
            r_stretta_millesimi: 54_477,
            c_larga_millesimi: 1_335,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["distinct", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.string_extract",
        in_memoria: Costo {
            a: 642_324,
            r_millesimi: 4_562,
            c_millesimi: 5,
            r_stretta_millesimi: 69_223,
            c_larga_millesimi: 738,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.string_length",
        in_memoria: Costo {
            a: 107_223,
            r_millesimi: 0,
            c_millesimi: 200,
            r_stretta_millesimi: 29_492,
            c_larga_millesimi: 315,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.string_pad",
        in_memoria: Costo {
            a: 219_433,
            r_millesimi: 0,
            c_millesimi: 434,
            r_stretta_millesimi: 62_669,
            c_larga_millesimi: 668,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.table_diff",
        in_memoria: Costo {
            a: 461_841,
            r_millesimi: 49_788,
            c_millesimi: 383,
            r_stretta_millesimi: 60_826,
            c_larga_millesimi: 867,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.text_normalize",
        in_memoria: Costo {
            a: 41_758,
            r_millesimi: 0,
            c_millesimi: 419,
            r_stretta_millesimi: 43_418,
            c_larga_millesimi: 463,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.timezone_convert",
        in_memoria: Costo {
            a: 583_358,
            r_millesimi: 0,
            c_millesimi: 640,
            r_stretta_millesimi: 118_375,
            c_larga_millesimi: 1_262,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.top_n",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 0,
            c_millesimi: 1_000,
            r_stretta_millesimi: 23_757,
            c_larga_millesimi: 332,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.transpose",
        in_memoria: Costo {
            a: 161_947,
            r_millesimi: 1_626_737,
            c_millesimi: 1_669,
            r_stretta_millesimi: 7_372_800,
            c_larga_millesimi: 36_950,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.type_cast",
        in_memoria: Costo {
            a: 97_283,
            r_millesimi: 11_981,
            c_millesimi: 0,
            r_stretta_millesimi: 18_432,
            c_larga_millesimi: 232,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.union_distinct",
        in_memoria: Costo {
            a: 118_315,
            r_millesimi: 49_876,
            c_millesimi: 2_731,
            r_stretta_millesimi: 88_064,
            c_larga_millesimi: 3_100,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: Some(Costo {
            a: 999_446,
            r_millesimi: 0,
            c_millesimi: 1_764,
            r_stretta_millesimi: 132_711,
            c_larga_millesimi: 1_800,
            k_millesimi: 0,
            p_millesimi: 0,
        }),
        dipende_dai_dati: false,
        profili: &[
            "distinct",
            "narrow",
            "spilled_distinct",
            "spilled_wide",
            "wide",
        ],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.unnest",
        in_memoria: Costo {
            a: 51_883,
            r_millesimi: 16_931,
            c_millesimi: 0,
            r_stretta_millesimi: 22_119,
            c_larga_millesimi: 399,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.uuid_generator",
        in_memoria: Costo {
            a: 291_396,
            r_millesimi: 98_247,
            c_millesimi: 0,
            r_stretta_millesimi: 111_412,
            c_larga_millesimi: 1_358,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.validate_rules",
        in_memoria: Costo {
            a: 213_779,
            r_millesimi: 8_933,
            c_millesimi: 0,
            r_stretta_millesimi: 26_624,
            c_larga_millesimi: 323,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["narrow", "wide"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "table.window_function",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 13_932,
            c_millesimi: 2_176,
            r_stretta_millesimi: 63_079,
            c_larga_millesimi: 2_278,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["distinct", "narrow", "wide"],
        esclusi: &[],
    },
];
