//! Modello di costo delle operazioni geo: GENERATO da
//! `scripts/genera_costi_geo.py`, non si modifica a mano.
//!
//! Fonte: `data/misure/catalogo-memoria-v4.json` (campagna Windows v4 a
//! `24698d6`, geo al livello del runner: colonne GeoArrow-WKB,
//! decodifica con validazione OGC, kernel, codifica; SHA-256 in
//! [`SHA256_MISURE`]). Stessa forma e stesse regole delle tabellari
//! ([`crate::costi_operazioni`], `scripts/modello_costi.py`); le classi di
//! larghezza sono profilo per vertici per geometria, e `generate_grid` ha
//! solo il termine per cella d'uscita. I profili in `esclusi` non entrano
//! nel modello (motivi in `scripts/genera_costi_geo.py`): limite
//! dichiarato in docs/runner.md, «Modelli di costo geo».

use crate::budget::{Costo, CostoOperazione};

/// SHA-256 delle misure da cui il modello e' generato.
pub const SHA256_MISURE: &str = "9057ae26a04f9c1868b9c99766f60a26147d80606b8e62f62d3255be9ba2bf07";

/// Un modello per operazione geo del catalogo, in ordine di id.
pub static COSTI_GEO: &[CostoOperazione] = &[
    CostoOperazione {
        op: "geo.affine_transform",
        in_memoria: Costo {
            a: 925_696,
            r_millesimi: 0,
            c_millesimi: 2_569,
            r_stretta_millesimi: 925_696,
            c_larga_millesimi: 1_907,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.area",
        in_memoria: Costo {
            a: 643_072,
            r_millesimi: 876_438,
            c_millesimi: 214,
            r_stretta_millesimi: 643_072,
            c_larga_millesimi: 309,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.bearing",
        in_memoria: Costo {
            a: 507_904,
            r_millesimi: 0,
            c_millesimi: 495,
            r_stretta_millesimi: 507_904,
            c_larga_millesimi: 8_756,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.boundary",
        in_memoria: Costo {
            a: 962_560,
            r_millesimi: 0,
            c_millesimi: 2_426,
            r_stretta_millesimi: 962_560,
            c_larga_millesimi: 1_706,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.bounds_extractor",
        in_memoria: Costo {
            a: 651_264,
            r_millesimi: 49_564,
            c_millesimi: 831,
            r_stretta_millesimi: 651_264,
            c_larga_millesimi: 366,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.buffer",
        in_memoria: Costo {
            a: 10_407_936,
            r_millesimi: 711_759,
            c_millesimi: 24_125,
            r_stretta_millesimi: 10_407_936,
            c_larga_millesimi: 16_085,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_zigzag", "default"],
        esclusi: &["adversarial_zigzag"],
    },
    CostoOperazione {
        op: "geo.centroid",
        in_memoria: Costo {
            a: 720_896,
            r_millesimi: 28_803,
            c_millesimi: 912,
            r_stretta_millesimi: 720_896,
            c_larga_millesimi: 239,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.clean_topology",
        in_memoria: Costo {
            a: 1_748_992,
            r_millesimi: 782_257,
            c_millesimi: 4_916,
            r_stretta_millesimi: 3_047_424,
            c_larga_millesimi: 4_411,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_overlaps", "default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.clip",
        in_memoria: Costo {
            a: 1_658_880,
            r_millesimi: 143_743,
            c_millesimi: 3_389,
            r_stretta_millesimi: 1_657_223,
            c_larga_millesimi: 3_056,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.cluster_dbscan",
        in_memoria: Costo {
            a: 582_177,
            r_millesimi: 0,
            c_millesimi: 10_214,
            r_stretta_millesimi: 790_528,
            c_larga_millesimi: 25_318,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["adversarial_dense", "default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.collect",
        in_memoria: Costo {
            a: 471_040,
            r_millesimi: 0,
            c_millesimi: 5_288,
            r_stretta_millesimi: 471_040,
            c_larga_millesimi: 14_273,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.concave_hull",
        in_memoria: Costo {
            a: 1_249_280,
            r_millesimi: 0,
            c_millesimi: 4_813,
            r_stretta_millesimi: 1_249_280,
            c_larga_millesimi: 1_534,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.convex_hull",
        in_memoria: Costo {
            a: 1_093_632,
            r_millesimi: 443,
            c_millesimi: 2_075,
            r_stretta_millesimi: 1_093_632,
            c_larga_millesimi: 501,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.count_points_in_polygons",
        in_memoria: Costo {
            a: 1_103_181,
            r_millesimi: 191_593,
            c_millesimi: 1_072,
            r_stretta_millesimi: 817_152,
            c_larga_millesimi: 1_103,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_all_candidates", "default"],
        esclusi: &["adversarial_all_candidates"],
    },
    CostoOperazione {
        op: "geo.coverage_validate",
        in_memoria: Costo {
            a: 1_425_408,
            r_millesimi: 338_909,
            c_millesimi: 2_409,
            r_stretta_millesimi: 1_425_408,
            c_larga_millesimi: 2_303,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_overlaps", "default"],
        esclusi: &["adversarial_overlaps"],
    },
    CostoOperazione {
        op: "geo.delaunay",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 0,
            c_millesimi: 31_915,
            r_stretta_millesimi: 2_301_952,
            c_larga_millesimi: 31_915,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.densify",
        in_memoria: Costo {
            a: 10_137_113,
            r_millesimi: 13_873_236,
            c_millesimi: 8_196,
            r_stretta_millesimi: 24_870_912,
            c_larga_millesimi: 9_128,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.difference",
        in_memoria: Costo {
            a: 2_187_264,
            r_millesimi: 0,
            c_millesimi: 4_103,
            r_stretta_millesimi: 1_093_632,
            c_larga_millesimi: 1_880,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.dissolve",
        in_memoria: Costo {
            a: 0,
            r_millesimi: 16_555_571,
            c_millesimi: 22_810,
            r_stretta_millesimi: 18_950_554,
            c_larga_millesimi: 14_070,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_overlaps", "default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.distance",
        in_memoria: Costo {
            a: 618_496,
            r_millesimi: 10_318,
            c_millesimi: 239,
            r_stretta_millesimi: 618_496,
            c_larga_millesimi: 202,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.envelope",
        in_memoria: Costo {
            a: 958_464,
            r_millesimi: 1_152_787,
            c_millesimi: 119,
            r_stretta_millesimi: 958_464,
            c_larga_millesimi: 251,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.explode",
        in_memoria: Costo {
            a: 817_371,
            r_millesimi: 108_430,
            c_millesimi: 2_306,
            r_stretta_millesimi: 1_163_264,
            c_larga_millesimi: 1_987,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.frechet_distance",
        in_memoria: Costo {
            a: 274_432,
            r_millesimi: 174_795,
            c_millesimi: 113,
            r_stretta_millesimi: 471_040,
            c_larga_millesimi: 127,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.from_coords",
        in_memoria: Costo {
            a: 462_848,
            r_millesimi: 0,
            c_millesimi: 4_796,
            r_stretta_millesimi: 462_848,
            c_larga_millesimi: 19_286,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.from_wkt",
        in_memoria: Costo {
            a: 1_097_728,
            r_millesimi: 62_444,
            c_millesimi: 1_685,
            r_stretta_millesimi: 1_097_728,
            c_larga_millesimi: 881,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.generate_grid",
        in_memoria: Costo {
            a: 23_883,
            r_millesimi: 452_678,
            c_millesimi: 0,
            r_stretta_millesimi: 0,
            c_larga_millesimi: 0,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.geodesic_area",
        in_memoria: Costo {
            a: 811_008,
            r_millesimi: 18_989,
            c_millesimi: 822,
            r_stretta_millesimi: 811_008,
            c_larga_millesimi: 343,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.geodesic_distance",
        in_memoria: Costo {
            a: 450_560,
            r_millesimi: 0,
            c_millesimi: 467,
            r_stretta_millesimi: 450_560,
            c_larga_millesimi: 7_768,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.geodesic_line_length",
        in_memoria: Costo {
            a: 569_344,
            r_millesimi: 104_196,
            c_millesimi: 157,
            r_stretta_millesimi: 569_344,
            c_larga_millesimi: 199,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.geometry_accessors",
        in_memoria: Costo {
            a: 745_472,
            r_millesimi: 51_316,
            c_millesimi: 807,
            r_stretta_millesimi: 745_472,
            c_larga_millesimi: 386,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.geometry_diagnostics",
        in_memoria: Costo {
            a: 737_280,
            r_millesimi: 80_672,
            c_millesimi: 477,
            r_stretta_millesimi: 737_280,
            c_larga_millesimi: 366,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.hausdorff_distance",
        in_memoria: Costo {
            a: 565_248,
            r_millesimi: 0,
            c_millesimi: 435,
            r_stretta_millesimi: 565_248,
            c_larga_millesimi: 134,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.haversine_distance",
        in_memoria: Costo {
            a: 356_352,
            r_millesimi: 0,
            c_millesimi: 481,
            r_stretta_millesimi: 356_352,
            c_larga_millesimi: 6_144,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.intersection",
        in_memoria: Costo {
            a: 1_609_728,
            r_millesimi: 0,
            c_millesimi: 3_903,
            r_stretta_millesimi: 804_864,
            c_larga_millesimi: 1_451,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.length",
        in_memoria: Costo {
            a: 446_464,
            r_millesimi: 97_485,
            c_millesimi: 142,
            r_stretta_millesimi: 446_464,
            c_larga_millesimi: 176,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.line_builder",
        in_memoria: Costo {
            a: 409_600,
            r_millesimi: 0,
            c_millesimi: 4_940,
            r_stretta_millesimi: 409_600,
            c_larga_millesimi: 12_411,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.line_interpolate_point",
        in_memoria: Costo {
            a: 565_248,
            r_millesimi: 96_469,
            c_millesimi: 185,
            r_stretta_millesimi: 565_248,
            c_larga_millesimi: 226,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.line_locate_point",
        in_memoria: Costo {
            a: 507_904,
            r_millesimi: 96_026,
            c_millesimi: 161,
            r_stretta_millesimi: 507_904,
            c_larga_millesimi: 199,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.line_merge",
        in_memoria: Costo {
            a: 596_185,
            r_millesimi: 103_780,
            c_millesimi: 2_803,
            r_stretta_millesimi: 983_040,
            c_larga_millesimi: 2_847,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.line_substring",
        in_memoria: Costo {
            a: 642_155,
            r_millesimi: 74_148,
            c_millesimi: 1_790,
            r_stretta_millesimi: 897_024,
            c_larga_millesimi: 1_549,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.make_valid",
        in_memoria: Costo {
            a: 1_015_808,
            r_millesimi: 3_176_866,
            c_millesimi: 14_840,
            r_stretta_millesimi: 1_015_808,
            c_larga_millesimi: 14_023,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_invalid", "default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.nearest",
        in_memoria: Costo {
            a: 1_028_489,
            r_millesimi: 0,
            c_millesimi: 7_875,
            r_stretta_millesimi: 774_144,
            c_larga_millesimi: 23_457,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_ties", "default"],
        esclusi: &["adversarial_ties"],
    },
    CostoOperazione {
        op: "geo.overlay",
        in_memoria: Costo {
            a: 1_611_930,
            r_millesimi: 1_002_903,
            c_millesimi: 9_202,
            r_stretta_millesimi: 2_775_040,
            c_larga_millesimi: 9_270,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_overlaps", "default"],
        esclusi: &["adversarial_overlaps"],
    },
    CostoOperazione {
        op: "geo.perimeter",
        in_memoria: Costo {
            a: 610_304,
            r_millesimi: 22_655,
            c_millesimi: 885,
            r_stretta_millesimi: 610_304,
            c_larga_millesimi: 356,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.point_on_surface",
        in_memoria: Costo {
            a: 1_900_544,
            r_millesimi: 0,
            c_millesimi: 3_297,
            r_stretta_millesimi: 1_900_544,
            c_larga_millesimi: 753,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.polygon_builder",
        in_memoria: Costo {
            a: 589_824,
            r_millesimi: 0,
            c_millesimi: 7_633,
            r_stretta_millesimi: 589_824,
            c_larga_millesimi: 17_854,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.polygonize",
        in_memoria: Costo {
            a: 2_072_576,
            r_millesimi: 72_717_684,
            c_millesimi: 20_004,
            r_stretta_millesimi: 2_072_576,
            c_larga_millesimi: 69_126,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_grid", "default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_contains",
        in_memoria: Costo {
            a: 1_642_496,
            r_millesimi: 0,
            c_millesimi: 997,
            r_stretta_millesimi: 1_642_496,
            c_larga_millesimi: 456,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_contains_properly",
        in_memoria: Costo {
            a: 1_568_768,
            r_millesimi: 0,
            c_millesimi: 1_123,
            r_stretta_millesimi: 1_568_768,
            c_larga_millesimi: 451,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_covered_by",
        in_memoria: Costo {
            a: 1_671_168,
            r_millesimi: 0,
            c_millesimi: 998,
            r_stretta_millesimi: 1_671_168,
            c_larga_millesimi: 464,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_covers",
        in_memoria: Costo {
            a: 1_622_016,
            r_millesimi: 0,
            c_millesimi: 974,
            r_stretta_millesimi: 1_622_016,
            c_larga_millesimi: 435,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_crosses",
        in_memoria: Costo {
            a: 1_642_496,
            r_millesimi: 0,
            c_millesimi: 981,
            r_stretta_millesimi: 1_642_496,
            c_larga_millesimi: 446,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_disjoint",
        in_memoria: Costo {
            a: 1_662_976,
            r_millesimi: 0,
            c_millesimi: 987,
            r_stretta_millesimi: 1_662_976,
            c_larga_millesimi: 454,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_equals_topo",
        in_memoria: Costo {
            a: 1_646_592,
            r_millesimi: 0,
            c_millesimi: 1_137,
            r_stretta_millesimi: 1_646_592,
            c_larga_millesimi: 447,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_intersects",
        in_memoria: Costo {
            a: 1_646_592,
            r_millesimi: 0,
            c_millesimi: 976,
            r_stretta_millesimi: 1_646_592,
            c_larga_millesimi: 466,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_overlaps",
        in_memoria: Costo {
            a: 1_658_880,
            r_millesimi: 0,
            c_millesimi: 1_045,
            r_stretta_millesimi: 1_658_880,
            c_larga_millesimi: 436,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_touches",
        in_memoria: Costo {
            a: 1_646_592,
            r_millesimi: 0,
            c_millesimi: 926,
            r_stretta_millesimi: 1_646_592,
            c_larga_millesimi: 436,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.predicate_within",
        in_memoria: Costo {
            a: 1_679_360,
            r_millesimi: 0,
            c_millesimi: 990,
            r_stretta_millesimi: 1_679_360,
            c_larga_millesimi: 447,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.reproject",
        in_memoria: Costo {
            a: 1_867_776,
            r_millesimi: 131_859,
            c_millesimi: 2_439,
            r_stretta_millesimi: 1_867_776,
            c_larga_millesimi: 2_416,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.rotate",
        in_memoria: Costo {
            a: 966_656,
            r_millesimi: 0,
            c_millesimi: 2_413,
            r_stretta_millesimi: 966_656,
            c_larga_millesimi: 1_993,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.scale",
        in_memoria: Costo {
            a: 917_504,
            r_millesimi: 0,
            c_millesimi: 2_463,
            r_stretta_millesimi: 917_504,
            c_larga_millesimi: 1_929,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.shared_paths",
        in_memoria: Costo {
            a: 792_329,
            r_millesimi: 284_298,
            c_millesimi: 5_003,
            r_stretta_millesimi: 1_548_288,
            c_larga_millesimi: 4_904,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.simplify",
        in_memoria: Costo {
            a: 1_187_840,
            r_millesimi: 0,
            c_millesimi: 5_296,
            r_stretta_millesimi: 1_187_840,
            c_larga_millesimi: 2_309,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.sjoin",
        in_memoria: Costo {
            a: 1_129_483,
            r_millesimi: 0,
            c_millesimi: 3_747,
            r_stretta_millesimi: 823_296,
            c_larga_millesimi: 11_932,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_all_candidates", "default"],
        esclusi: &["adversarial_all_candidates"],
    },
    CostoOperazione {
        op: "geo.snap",
        in_memoria: Costo {
            a: 1_380_352,
            r_millesimi: 0,
            c_millesimi: 2_377,
            r_stretta_millesimi: 1_380_352,
            c_larga_millesimi: 1_963,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.snap_to_grid",
        in_memoria: Costo {
            a: 995_328,
            r_millesimi: 0,
            c_millesimi: 2_535,
            r_stretta_millesimi: 995_328,
            c_larga_millesimi: 2_019,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.split",
        in_memoria: Costo {
            a: 589_364,
            r_millesimi: 0,
            c_millesimi: 12_052,
            r_stretta_millesimi: 876_544,
            c_larga_millesimi: 10_045,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_zigzag", "default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.subdivide",
        in_memoria: Costo {
            a: 1_155_072,
            r_millesimi: 0,
            c_millesimi: 6_995,
            r_stretta_millesimi: 1_155_072,
            c_larga_millesimi: 4_538,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.symmetric_difference",
        in_memoria: Costo {
            a: 3_653_632,
            r_millesimi: 0,
            c_millesimi: 5_117,
            r_stretta_millesimi: 1_826_816,
            c_larga_millesimi: 3_701,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.to_wkt",
        in_memoria: Costo {
            a: 1_134_592,
            r_millesimi: 0,
            c_millesimi: 4_907,
            r_stretta_millesimi: 1_134_592,
            c_larga_millesimi: 3_756,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.translate",
        in_memoria: Costo {
            a: 921_600,
            r_millesimi: 0,
            c_millesimi: 2_473,
            r_stretta_millesimi: 921_600,
            c_larga_millesimi: 1_941,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.union",
        in_memoria: Costo {
            a: 2_052_096,
            r_millesimi: 0,
            c_millesimi: 4_564,
            r_stretta_millesimi: 1_026_048,
            c_larga_millesimi: 1_941,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.vertex_count",
        in_memoria: Costo {
            a: 565_248,
            r_millesimi: 11_543,
            c_millesimi: 928,
            r_stretta_millesimi: 565_248,
            c_larga_millesimi: 391,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: false,
        profili: &["default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.voronoi",
        in_memoria: Costo {
            a: 1_034_373,
            r_millesimi: 0,
            c_millesimi: 23_763,
            r_stretta_millesimi: 1_769_472,
            c_larga_millesimi: 55_104,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_lattice", "default"],
        esclusi: &[],
    },
    CostoOperazione {
        op: "geo.within",
        in_memoria: Costo {
            a: 1_036_434,
            r_millesimi: 0,
            c_millesimi: 3_858,
            r_stretta_millesimi: 784_384,
            c_larga_millesimi: 11_368,
            k_millesimi: 0,
            p_millesimi: 0,
        },
        dipende_dai_dati: true,
        profili: &["adversarial_all_candidates", "default"],
        esclusi: &["adversarial_all_candidates"],
    },
];
