//! Modello di costo PROVVISORIO delle operazioni geo: GENERATO da
//! `scripts/genera_costi_geo.py`, non si modifica a mano.
//!
//! Fonte: `data/misure/profili-geo-memory-lab.json` (SHA-256 in
//! [`SHA256_PROFILI_GEO`]), estratto dal catalogo empirico di
//! `plenora-memory-lab` (SHA-256 del catalogo nel file). I kernel sono
//! misurati su geometrie gia' decodificate, senza gli adapter Arrow del
//! runner: le costanti aggiungono decodifica e uscita codificata
//! (formula nell'intestazione del generatore). Provvisorio finche' le
//! operazioni geo non sono rimisurate sul runner (README, «Budget di
//! memoria»).

use crate::budget::{Costo, CostoOperazione};

/// SHA-256 dei profili geo da cui il modello e' generato.
pub const SHA256_PROFILI_GEO: &str =
    "5ae9ed270833a72a0d859e4abd9f740e756ea6c475c4e4b144dbccbf8bd5b77b";

/// Un modello per operazione geo del catalogo, in ordine di id.
pub static COSTI_GEO: &[CostoOperazione] = &[
    CostoOperazione {
        op: "geo.affine_transform",
        in_memoria: Costo {
            a: 4_435_968,
            r_millesimi: 0,
            c_millesimi: 7_418,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.area",
        in_memoria: Costo {
            a: 4_272_128,
            r_millesimi: 0,
            c_millesimi: 4_180,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.bearing",
        in_memoria: Costo {
            a: 4_374_528,
            r_millesimi: 0,
            c_millesimi: 4_320,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.boundary",
        in_memoria: Costo {
            a: 4_456_448,
            r_millesimi: 0,
            c_millesimi: 8_142,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.bounds_extractor",
        in_memoria: Costo {
            a: 4_292_608,
            r_millesimi: 0,
            c_millesimi: 4_900,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.buffer",
        in_memoria: Costo {
            a: 4_993_024,
            r_millesimi: 0,
            c_millesimi: 57_146,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.centroid",
        in_memoria: Costo {
            a: 4_325_376,
            r_millesimi: 0,
            c_millesimi: 5_256,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.clean_topology",
        in_memoria: Costo {
            a: 4_505_600,
            r_millesimi: 0,
            c_millesimi: 68_432,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.clip",
        in_memoria: Costo {
            a: 4_567_040,
            r_millesimi: 0,
            c_millesimi: 39_284,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.cluster_dbscan",
        in_memoria: Costo {
            a: 4_739_072,
            r_millesimi: 0,
            c_millesimi: 26_686,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.collect",
        in_memoria: Costo {
            a: 4_292_608,
            r_millesimi: 0,
            c_millesimi: 8_260,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.concave_hull",
        in_memoria: Costo {
            a: 4_530_176,
            r_millesimi: 0,
            c_millesimi: 14_546,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.convex_hull",
        in_memoria: Costo {
            a: 4_489_216,
            r_millesimi: 0,
            c_millesimi: 7_416,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.count_points_in_polygons",
        in_memoria: Costo {
            a: 5_742_592,
            r_millesimi: 0,
            c_millesimi: 9_462,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.coverage_validate",
        in_memoria: Costo {
            a: 4_562_944,
            r_millesimi: 0,
            c_millesimi: 15_414,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.delaunay",
        in_memoria: Costo {
            a: 4_354_048,
            r_millesimi: 0,
            c_millesimi: 41_454,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.densify",
        in_memoria: Costo {
            a: 4_521_984,
            r_millesimi: 0,
            c_millesimi: 6_920,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.difference",
        in_memoria: Costo {
            a: 4_468_736,
            r_millesimi: 0,
            c_millesimi: 8_190,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.dissolve",
        in_memoria: Costo {
            a: 4_562_944,
            r_millesimi: 0,
            c_millesimi: 33_032,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.distance",
        in_memoria: Costo {
            a: 4_292_608,
            r_millesimi: 0,
            c_millesimi: 4_180,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.envelope",
        in_memoria: Costo {
            a: 4_427_776,
            r_millesimi: 0,
            c_millesimi: 7_418,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.explode",
        in_memoria: Costo {
            a: 4_816_896,
            r_millesimi: 0,
            c_millesimi: 7_182,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.frechet_distance",
        in_memoria: Costo {
            a: 4_288_512,
            r_millesimi: 0,
            c_millesimi: 5_312,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.from_coords",
        in_memoria: Costo {
            a: 4_276_224,
            r_millesimi: 0,
            c_millesimi: 10_986,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.from_wkt",
        in_memoria: Costo {
            a: 4_976_640,
            r_millesimi: 0,
            c_millesimi: 15_302,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.generate_grid",
        in_memoria: Costo {
            a: 4_431_872,
            r_millesimi: 539_136,
            c_millesimi: 0,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.geodesic_area",
        in_memoria: Costo {
            a: 4_395_008,
            r_millesimi: 0,
            c_millesimi: 4_180,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.geodesic_distance",
        in_memoria: Costo {
            a: 4_325_376,
            r_millesimi: 0,
            c_millesimi: 4_328,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.geodesic_line_length",
        in_memoria: Costo {
            a: 4_325_376,
            r_millesimi: 0,
            c_millesimi: 4_118,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.geometry_accessors",
        in_memoria: Costo {
            a: 4_472_832,
            r_millesimi: 0,
            c_millesimi: 6_458,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.geometry_diagnostics",
        in_memoria: Costo {
            a: 4_366_336,
            r_millesimi: 0,
            c_millesimi: 6_156,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.hausdorff_distance",
        in_memoria: Costo {
            a: 4_263_936,
            r_millesimi: 0,
            c_millesimi: 4_158,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.haversine_distance",
        in_memoria: Costo {
            a: 4_251_648,
            r_millesimi: 0,
            c_millesimi: 4_320,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.intersection",
        in_memoria: Costo {
            a: 4_476_928,
            r_millesimi: 0,
            c_millesimi: 7_572,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.length",
        in_memoria: Costo {
            a: 4_255_744,
            r_millesimi: 0,
            c_millesimi: 4_118,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.line_builder",
        in_memoria: Costo {
            a: 4_296_704,
            r_millesimi: 0,
            c_millesimi: 7_390,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.line_interpolate_point",
        in_memoria: Costo {
            a: 4_333_568,
            r_millesimi: 0,
            c_millesimi: 4_816,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.line_locate_point",
        in_memoria: Costo {
            a: 4_272_128,
            r_millesimi: 0,
            c_millesimi: 4_234,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.line_merge",
        in_memoria: Costo {
            a: 4_370_432,
            r_millesimi: 0,
            c_millesimi: 7_866,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.line_substring",
        in_memoria: Costo {
            a: 4_517_888,
            r_millesimi: 0,
            c_millesimi: 6_920,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.make_valid",
        in_memoria: Costo {
            a: 5_476_352,
            r_millesimi: 0,
            c_millesimi: 12_100,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["geos:cold", "geos:warm"],
    },
    CostoOperazione {
        op: "geo.nearest",
        in_memoria: Costo {
            a: 5_677_056,
            r_millesimi: 0,
            c_millesimi: 37_536,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.overlay",
        in_memoria: Costo {
            a: 5_857_280,
            r_millesimi: 0,
            c_millesimi: 28_546,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.perimeter",
        in_memoria: Costo {
            a: 4_259_840,
            r_millesimi: 0,
            c_millesimi: 4_180,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.point_on_surface",
        in_memoria: Costo {
            a: 4_575_232,
            r_millesimi: 0,
            c_millesimi: 5_258,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.polygon_builder",
        in_memoria: Costo {
            a: 4_247_552,
            r_millesimi: 0,
            c_millesimi: 14_696,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.polygonize",
        in_memoria: Costo {
            a: 5_046_272,
            r_millesimi: 0,
            c_millesimi: 72_498,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["geos:cold", "geos:warm"],
    },
    CostoOperazione {
        op: "geo.predicate_contains",
        in_memoria: Costo {
            a: 4_481_024,
            r_millesimi: 0,
            c_millesimi: 4_048,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_contains_properly",
        in_memoria: Costo {
            a: 4_485_120,
            r_millesimi: 0,
            c_millesimi: 4_034,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_covered_by",
        in_memoria: Costo {
            a: 4_485_120,
            r_millesimi: 0,
            c_millesimi: 4_042,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_covers",
        in_memoria: Costo {
            a: 4_485_120,
            r_millesimi: 0,
            c_millesimi: 4_042,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_crosses",
        in_memoria: Costo {
            a: 4_579_328,
            r_millesimi: 0,
            c_millesimi: 4_008,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_disjoint",
        in_memoria: Costo {
            a: 4_485_120,
            r_millesimi: 0,
            c_millesimi: 4_034,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_equals_topo",
        in_memoria: Costo {
            a: 4_485_120,
            r_millesimi: 0,
            c_millesimi: 4_034,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_intersects",
        in_memoria: Costo {
            a: 4_485_120,
            r_millesimi: 0,
            c_millesimi: 4_042,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_overlaps",
        in_memoria: Costo {
            a: 4_476_928,
            r_millesimi: 0,
            c_millesimi: 4_042,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_touches",
        in_memoria: Costo {
            a: 4_481_024,
            r_millesimi: 0,
            c_millesimi: 4_048,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.predicate_within",
        in_memoria: Costo {
            a: 4_485_120,
            r_millesimi: 0,
            c_millesimi: 4_034,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.reproject",
        in_memoria: Costo {
            a: 4_333_568,
            r_millesimi: 0,
            c_millesimi: 7_736,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &[
            "proj:monte_mario_wgs84",
            "proj:noop_wgs84",
            "proj:utm32n_web_mercator",
            "proj:wgs84_utm32n",
            "proj:wgs84_web_mercator",
        ],
    },
    CostoOperazione {
        op: "geo.rotate",
        in_memoria: Costo {
            a: 4_460_544,
            r_millesimi: 0,
            c_millesimi: 7_416,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.scale",
        in_memoria: Costo {
            a: 4_448_256,
            r_millesimi: 0,
            c_millesimi: 7_418,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.shared_paths",
        in_memoria: Costo {
            a: 4_411_392,
            r_millesimi: 0,
            c_millesimi: 22_104,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.simplify",
        in_memoria: Costo {
            a: 4_440_064,
            r_millesimi: 0,
            c_millesimi: 5_758,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.sjoin",
        in_memoria: Costo {
            a: 5_767_168,
            r_millesimi: 0,
            c_millesimi: 8_910,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.snap",
        in_memoria: Costo {
            a: 4_554_752,
            r_millesimi: 0,
            c_millesimi: 6_920,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.snap_to_grid",
        in_memoria: Costo {
            a: 4_509_696,
            r_millesimi: 0,
            c_millesimi: 6_920,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.split",
        in_memoria: Costo {
            a: 5_496_832,
            r_millesimi: 0,
            c_millesimi: 41_454,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["classe:espansioni", "geos:cold", "geos:warm"],
    },
    CostoOperazione {
        op: "geo.subdivide",
        in_memoria: Costo {
            a: 5_308_416,
            r_millesimi: 0,
            c_millesimi: 7_594,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.symmetric_difference",
        in_memoria: Costo {
            a: 4_759_552,
            r_millesimi: 0,
            c_millesimi: 11_512,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.to_wkt",
        in_memoria: Costo {
            a: 4_431_872,
            r_millesimi: 0,
            c_millesimi: 6_356,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.translate",
        in_memoria: Costo {
            a: 4_440_064,
            r_millesimi: 0,
            c_millesimi: 7_416,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.union",
        in_memoria: Costo {
            a: 4_489_216,
            r_millesimi: 0,
            c_millesimi: 9_118,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.vertex_count",
        in_memoria: Costo {
            a: 4_259_840,
            r_millesimi: 0,
            c_millesimi: 4_180,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.voronoi",
        in_memoria: Costo {
            a: 4_644_864,
            r_millesimi: 0,
            c_millesimi: 52_268,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: true,
        profili: &["rust:default"],
    },
    CostoOperazione {
        op: "geo.within",
        in_memoria: Costo {
            a: 5_787_648,
            r_millesimi: 0,
            c_millesimi: 9_032,
            p_millesimi: 0,
        },
        spill: None,
        dipende_dai_dati: false,
        profili: &["rust:default"],
    },
];
